spring:
  application:
    name: league-api
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/meeple_league}
    username: ${DB_USERNAME:meeple_league}
    password: ${DB_PASSWORD:meeple_league_local}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': true
    show-sql: true
  flyway:
    default-schema: league
    schemas: league,shared

logging:
  level:
    '[io.arpicode.leagueapi]': DEBUG
